### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by knutole** [mapic/mitt-distrikt#1]
## Avklaringer
- [x] Domenenavn? Lier2030.no?
- [x] Design og uttrykk
- [x] Facebook side? 
- [x] Gjenbruk, få alle behov avklart (spesielt i forhold til parallell bruk)
- [x] Definere alt som skal kunne konfigureres på admin-siden

----

## Backend
- [x] Registrere domenenavn
- [x] SSL sertifikat @ Let's Encrypt
- [x] Sette opp AWS EC2
- [ ] Sette opp S3 lagring
- [x] Åpne Github repository
- [x] Sette opp Google Analytics
- [x] Sette opp Facebook App + Page (?)
- [x] GoNative.io
- [ ] [Redis-cache ](https://ttmm.io/tech/ludicrous-speed-wordpress-caching-with-redis/)for Wordpress
- [x] API endpoints (with wp redirect)
- [x] Definere Docker image

## Docker image
- [x] Ubuntu
- [x] NodeJS
- [x] Nginx
- [x] Nginx config file
- [x] `yarn`, `nodemon`, `forever`
- [x] Redis
- [x] Redis config file
- [x] Wordpress

#### Frame, Info, Media
- [x] Responsive boilerplate
- [x] Tabs
- [x] Admin-link for desktop version
- [x] Wordpress, stripped 
- [x] Instagram account
- [ ] Embedding

#### Kart
- [x] Mapbox GL JS
- [x] Plugin for adding notes
- [x] Uploading of photo/video directly to s3
- [x] GeoJSON notes
- [x] Social media plugins

### Admin
- [x] Login
- [x] Tabs
- [x] Wordpress, create posts (stripped)
- [x] Table of map notes, with 
    - [x] delete
    - [x] export
    - [x] tags
    - [x] sortable
    - [ ] etc
- [ ] Config
    - [ ] set current active tag for notes
    - [ ] set instagram #hashtag or search word
    - [ ] other settings?
- [ ] `.json` file for all text content
- [ ] Eksportering til `.csv` etc.
- [ ] Google Analytics viewer

## Tests
- [ ] API
- [ ] Frontend functionality
- [ ] Stress-tests

##  Åpen kildekode, dokumentasjon
- [x] Brukerveiledning
- [ ] Tutorials, user guide for utvikling
- [ ] Install scripts
