### ISSUE TITLE
frontend todo

### ISSUE THREAD

**Issue by knutole** [mapic/mitt-distrikt#11]
### page
- [x] fix buttons with different screen sizes
- [x] fix page with diff sizes
- [x] add title on desktop version
- [x] fix flash logo on app

### info
- [x] design wordpress
- [x] strip frontend of wordpress
- [x] strip backend of wordpress

### media
- [x] style posts
- [x] ensure looks good on all screens
- [x] add title on top
- [x] add `/uploads/` storage container to wordpress

### map
- [x] add (+) button
- [x] ensure looks good on all screens
- [x] add "new note" screen .....
- [x] create plugin for notes
- [x] create notes on map, etc, etc

**Comment by knutole** [comment]
- [x] api for deleting records
- [x] access_token checks
- [ ] tests
- [ ] minimize, performance
- [x] save features separately and build geojson for each time.. less chance of corrupt geojson file
- [x] show short address
- [x] check input fields before post
- [x] uploading progress bar
- [x] close window immediately when posting note
- [x] navn på note
- [ ] ensure all `locale` is set
- [ ] splash screen with thank you and sharing to FB option after posting note  
- [x] social
- [ ] toggle background layer
- [x] facebook locale NO
- [x] double-check app icon resolution (and stroke)

### css
- [x] fix popup size for mobile (a bit smaller)
- [x] fix click on mobile on markers
- [x] fix "les mer" window
- [x] fix "add note" button to centre with transform



### and
- [x] more gon
- [ ] insta/twit gjennom proxy 
- [ ] admin for media (search-word)
- [x] admin css småpirk

**Comment by knutole** [comment]
### css
- [ ] fix popup size for mobile (a bit smaller)
- [ ] fix click on mobile on markers
- [ ] fix "les mer" window
- [ ] fix "add note" button to centre with transform

### and
- [ ] insta/twit gjennom proxy 
- [ ] admin for media (search-word)
- [ ] more gon
