### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by knutole** [mapic/mitt-distrikt#13]
### Features
- [x] export notes to .csv
- [x] set social media search tag
- [x] tests
- [x] documentation
- [x] install scripts
- [x] grunt, minify

### Tweaks
- [x] fix small design tweaks
- [x] get feedback
- [x] email notifications
- [x] open note on link redirect

### Bugs
- [x] date sorting in admin is wrong
- [x] default 100 views
- [x] Geocatchingen (eller hva det heter) fungerer ikke skikkelig. Man får ikke opp adressen der man står når man skal legge inn bilde
- [x] Går det an å endre teksten «flytt kartet til ønsket sted. Trykk så OK» til «flytt kartet til ønsket sted. Trykk ok for å gi innspill»
- [x] Hos noen «hang» appen da de prøvde å trykke på OK for å laste inn innlegg, slik at de ikke fikk det til
- [x] IE mask not supported
- [x] orientation on uploaded images. use [exif.js](https://stackoverflow.com/questions/19463126/how-to-draw-photo-with-correct-orientation-in-canvas-after-capture-photo-by-usin) (save exif orientation in geosjon on upload)

### spec
- [x] endre/slette eget innlegg - cookies
- [x] ~~deling med bilde av kartet~~ (deling med opplastet bilde istedet)
- [x] toggle background image
- [x] put all text in `locale` 
- [x] analytics email as pdf each week

### final final
- [x] 22. juni, lansering
- [x] fikse alle bugs/twitter før den tid.
