### ISSUE TITLE
Filtrere bilder i sosial medier feeden

### ISSUE THREAD

**Issue by knutole** [mapic/mitt-distrikt#14]
### Feature
Gjøre det mulig å filtrere bort uønskede bilder i sosial medier feeden.

### Todo
- [x] proxy feed thru server
- [x] create cache of images
- [x] instagram + twitter
- [x] tag each post with ID
- [x] GUI: replicate feed on admin page, with checkbox for filtering

**Comment by knutole** [comment]
done
